<?php
/** @var \Magento\WidgetConfigurationAdmin\Block\Adminhtml\Index $block */

?>

<div
    id="root"
    data-environment-id="<?= $block->escapeHtmlAttr($block->getEnvironmentId()); ?>"
    data-website-code="<?= $block->escapeHtmlAttr($block->getWebsiteCode()); ?>"
    data-store-view-code="<?= $block->escapeHtmlAttr($block->getStoreViewCode()); ?>"
    data-store-code="<?= $block->escapeHtmlAttr($block->getStoreCode()); ?>"
></div>

<script src="<?= $block->escapeUrl($block->getFrontendUrl()) ?>"></script>
